"use client";
import { FormEvent, useEffect, useState } from "react";
import { apiDownload, apiRequest, ApiError } from "@/lib/api";
import type { CustomerResponse, DocumentProcessingResponse, DocumentResponse, DocumentType, InvoiceExtraction, InvoiceResponse } from "@/lib/api";
import { PageHeading } from "@/components/ui/page-heading";

const labels:Record<DocumentType,string>={receipt:"Receipt",invoice_attachment:"Invoice attachment",other:"Other"};
function msg(e:unknown){return e instanceof ApiError?e.message:"Unable to complete this request."} function size(n:number){return n<1048576?`${Math.round(n/1024)} KB`:`${(n/1048576).toFixed(1)} MB`;}
export function DocumentsView(){
 const [docs,setDocs]=useState<DocumentResponse[]>([]),[customers,setCustomers]=useState<CustomerResponse[]>([]);const[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);const[selected,setSelected]=useState<DocumentResponse|null>(null),[processing,setProcessing]=useState<DocumentProcessingResponse|null>(null);const[upload,setUpload]=useState(false),[busy,setBusy]=useState(false),[formError,setFormError]=useState<string|null>(null),[confirmDelete,setConfirmDelete]=useState(false);
 useEffect(()=>{let c=false;Promise.all([apiRequest<DocumentResponse[]>("/documents",{query:{limit:100}}),apiRequest<CustomerResponse[]>("/customers",{query:{limit:100}})]).then(([d,u])=>{if(!c){setDocs(d);setCustomers(u)}}).catch(e=>{if(!c)setError(msg(e))}).finally(()=>{if(!c)setLoading(false)});return()=>{c=true}},[]);
 async function open(doc:DocumentResponse){setSelected(doc);setProcessing(null);setFormError(null);setConfirmDelete(false);try{setProcessing(await apiRequest<DocumentProcessingResponse>(`/documents/${doc.id}/processing`))}catch(e){if(!(e instanceof ApiError&&e.status===404))setFormError(msg(e))}}
 async function uploadFile(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setFormError(null);const fd=new FormData(e.currentTarget);try{const d=await apiRequest<DocumentResponse>("/documents",{method:"POST",body:fd});setDocs(v=>[d,...v]);setUpload(false)}catch(x){setFormError(msg(x))}finally{setBusy(false)}}
 async function process(){if(!selected)return;setBusy(true);setFormError(null);try{setProcessing(await apiRequest<DocumentProcessingResponse>(`/documents/${selected.id}/processing`,{method:"POST"}))}catch(e){setFormError(msg(e))}finally{setBusy(false)}}
 async function review(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected||!processing?.extracted_data)return;setBusy(true);const fd=new FormData(e.currentTarget),old=processing.extracted_data;const val=(k:string)=>String(fd.get(k)??"").trim()||null;const extracted_data:InvoiceExtraction={...old,supplier_name:val("supplier_name"),supplier_email:val("supplier_email"),customer_name:val("customer_name"),invoice_number:val("invoice_number"),currency:val("currency"),issue_date:val("issue_date"),due_date:val("due_date"),notes:val("notes")};try{setProcessing(await apiRequest<DocumentProcessingResponse>(`/documents/${selected.id}/processing/review`,{method:"PATCH",body:{extracted_data}}))}catch(x){setFormError(msg(x))}finally{setBusy(false)}}
 async function createInvoice(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;setBusy(true);try{const fd=new FormData(e.currentTarget);const invoice=await apiRequest<InvoiceResponse>(`/documents/${selected.id}/processing/create-invoice`,{method:"POST",body:{customer_id:String(fd.get("customer_id"))}});setDocs(v=>v.map(d=>d.id===selected.id?{...d,invoice_id:invoice.id}:d));setSelected(s=>s?{...s,invoice_id:invoice.id}:s)}catch(x){setFormError(msg(x))}finally{setBusy(false)}}
 async function download(){if(!selected)return;try{const r=await apiDownload(`/documents/${selected.id}/download`);const url=URL.createObjectURL(await r.blob());const a=document.createElement("a");a.href=url;a.download=selected.original_filename;a.click();URL.revokeObjectURL(url)}catch(x){setFormError(msg(x))}}
 async function remove(){if(!selected)return;setBusy(true);try{await apiRequest<void>(`/documents/${selected.id}`,{method:"DELETE"});setDocs(v=>v.filter(d=>d.id!==selected.id));setSelected(null)}catch(x){setFormError(msg(x))}finally{setBusy(false)}}
 return <><PageHeading actions={<button className="button" onClick={()=>{setUpload(true);setFormError(null)}}>Upload document</button>} description="Upload files and turn paperwork into structured data." title="Documents"/>
 {loading?<div className="customer-list loading-list">{[1,2,3].map(x=><div className="customer-row skeleton-row" key={x}/>)}</div>:error?<div className="state-card error-state"><div className="state-icon">!</div><h2>Documents couldn’t load</h2><p>{error}</p></div>:docs.length===0?<div className="state-card"><div className="state-icon">↑</div><h2>Upload your first document</h2><p>PDF, JPEG, and PNG files up to 10 MB are supported.</p><button className="button" onClick={()=>setUpload(true)}>Upload document</button></div>:<div className="document-grid">{docs.map(d=><button className="document-card" key={d.id} onClick={()=>void open(d)}><span className="file-icon">{d.content_type==="application/pdf"?"PDF":"IMG"}</span><strong>{d.original_filename}</strong><small>{labels[d.document_type]} · {size(d.size_bytes)}</small><small>{new Date(d.created_at).toLocaleDateString("en-GB")}</small>{d.invoice_id?<i>Linked to invoice</i>:null}</button>)}</div>}
 {(upload||selected)?<div className="drawer-layer"><button className="drawer-backdrop" onClick={()=>!busy&&(setUpload(false),setSelected(null))}/><aside className="customer-drawer"><div className="drawer-heading"><div><span className="kicker">{upload?"New document":"Document"}</span><h2>{upload?"Upload document":selected?.original_filename}</h2></div><button className="icon-button" onClick={()=>{setUpload(false);setSelected(null)}}>×</button></div>{upload?<form className="customer-form" onSubmit={uploadFile}><div className="form-section upload-box"><input accept="application/pdf,image/jpeg,image/png" name="file" required type="file"/><p>PDF, JPEG, or PNG · maximum 10 MB</p></div><div className="form-section"><label className="form-control"><span>Document type</span><select name="document_type" defaultValue="other">{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label></div>{formError?<p className="form-error">{formError}</p>:null}<div className="drawer-actions"><span/><button className="button" disabled={busy}>{busy?"Uploading…":"Upload"}</button></div></form>:selected?<div className="document-detail"><div className="document-summary"><span className="file-icon large">{selected.content_type==="application/pdf"?"PDF":"IMG"}</span><div><strong>{selected.original_filename}</strong><small>{labels[selected.document_type]} · {size(selected.size_bytes)}</small></div><button className="button secondary" onClick={()=>void download()}>Download</button></div>
 <section className="form-section"><div className="line-heading"><h3>AI processing</h3><i className={`status-badge ${processing?.status??"draft"}`}>{processing?.status?.replace("_"," ")??"Not processed"}</i></div>{!processing?<><p className="section-copy">Extract invoice data with the configured AI provider.</p><button className="button" disabled={busy} onClick={()=>void process()}>{busy?"Processing…":"Process with AI"}</button></>:processing.error_message?<p className="form-error">{processing.error_message}</p>:processing.extracted_data?<form className="extraction-form" onSubmit={review}><div className="form-grid"><label className="form-control"><span>Supplier</span><input name="supplier_name" defaultValue={processing.extracted_data.supplier_name??""}/></label><label className="form-control"><span>Supplier email</span><input name="supplier_email" type="email" defaultValue={processing.extracted_data.supplier_email??""}/></label><label className="form-control"><span>Customer</span><input name="customer_name" defaultValue={processing.extracted_data.customer_name??""}/></label><label className="form-control"><span>Invoice number</span><input name="invoice_number" defaultValue={processing.extracted_data.invoice_number??""}/></label><label className="form-control"><span>Currency</span><input name="currency" maxLength={3} defaultValue={processing.extracted_data.currency??""}/></label><label className="form-control"><span>Issue date</span><input name="issue_date" type="date" defaultValue={processing.extracted_data.issue_date??""}/></label><label className="form-control"><span>Due date</span><input name="due_date" type="date" defaultValue={processing.extracted_data.due_date??""}/></label><label className="form-control full"><span>Notes</span><textarea name="notes" defaultValue={processing.extracted_data.notes??""}/></label></div><div className="extracted-lines">{processing.extracted_data.line_items?.map((line,i)=><div key={i}><span>{line.description||"Untitled item"}</span><strong>{line.quantity??"—"} × {line.unit_price??"—"} · {line.vat_rate??0}%</strong></div>)}</div>{processing.status==="review_required"?<button className="button" disabled={busy}>Approve review</button>:null}</form>:<p className="section-copy">Processing is {processing.status.replace("_"," ")}.</p>}</section>
 {processing?.status==="completed"&&!selected.invoice_id?<form className="form-section create-from-doc" onSubmit={createInvoice}><h3>Create invoice</h3><label className="form-control"><span>Choose customer</span><select name="customer_id" required><option value="">Select customer</option>{customers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><button className="button" disabled={busy}>Create invoice</button></form>:null}{selected.invoice_id?<div className="inline-notice">Invoice created and linked to this document.</div>:null}{formError?<p className="form-error">{formError}</p>:null}{confirmDelete?<div className="delete-confirm"><p>Delete this document and its stored file?</p><div><button className="text-button" onClick={()=>setConfirmDelete(false)}>Cancel</button><button className="danger-button" onClick={()=>void remove()}>Delete document</button></div></div>:<button className="text-button danger-text" onClick={()=>setConfirmDelete(true)}>Delete document</button>}</div>:null}</aside></div>:null}</>}
