"use client";
import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
import {apiRequest,ApiError} from "@/lib/api";
import type{CustomerResponse,DashboardResponse,InvoiceStatus}from"@/lib/api";
import{PageHeading}from"@/components/ui/page-heading";
function cash(v:string,c:string){return new Intl.NumberFormat("en-GB",{style:"currency",currency:c,maximumFractionDigits:0}).format(Number(v))}function msg(e:unknown){return e instanceof ApiError?e.message:"Dashboard could not load."}
export function DashboardView(){const[data,setData]=useState<DashboardResponse|null>(null),[customers,setCustomers]=useState<CustomerResponse[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);const[currency,setCurrency]=useState("GBP"),[months,setMonths]=useState(12),[status,setStatus]=useState<InvoiceStatus|"">(""),[customer,setCustomer]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState("");
useEffect(()=>{let cancel=false;Promise.all([apiRequest<DashboardResponse>("/dashboard",{query:{currency,months,invoice_status:status||undefined,customer_id:customer||undefined,date_from:from||undefined,date_to:to||undefined}}),apiRequest<CustomerResponse[]>("/customers",{query:{limit:100}})]).then(([d,c])=>{if(!cancel){setData(d);setCustomers(c);setError(null)}}).catch(e=>{if(!cancel)setError(msg(e))}).finally(()=>{if(!cancel)setLoading(false)});return()=>{cancel=true}},[currency,months,status,customer,from,to]);
const maxCash=Math.max(1,...(data?.monthly_cash_flow.map(x=>Number(x.amount))??[]));const maxStatus=Math.max(1,...(data?.invoice_statuses.map(x=>x.count)??[]));const active=useMemo(()=>[status,customer,from,to].filter(Boolean).length,[status,customer,from,to]);
return <><PageHeading description="Track performance and move from insight to action." title="Dashboard"/><div className="dashboard-filters"><select value={currency} onChange={e=>setCurrency(e.target.value)}><option>GBP</option><option>USD</option><option>EUR</option></select><select value={months} onChange={e=>setMonths(Number(e.target.value))}><option value={6}>6 months</option><option value={12}>12 months</option><option value={24}>24 months</option></select><select value={status} onChange={e=>setStatus(e.target.value as InvoiceStatus|"")}><option value="">All statuses</option>{["draft","sent","paid","overdue","cancelled"].map(s=><option key={s}>{s}</option>)}</select><select value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">All customers</option>{customers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><input aria-label="From date" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input aria-label="To date" type="date" value={to} onChange={e=>setTo(e.target.value)}/>{active?<button onClick={()=>{setStatus("");setCustomer("");setFrom("");setTo("")}}>Clear {active}</button>:null}</div>
{loading?<div className="loading-grid">{[1,2,3,4].map(x=><div className="skeleton-card" key={x}><span/><span/><span/></div>)}</div>:error?<div className="state-card error-state"><div className="state-icon">!</div><h2>Dashboard couldn’t load</h2><p>{error}</p></div>:data?<><section className="live-kpis"><Link href="/payments"><span>Revenue received</span><strong>{cash(data.kpis.total_revenue,data.currency)}</strong><small>For selected period</small></Link><Link href="/invoices"><span>Outstanding</span><strong>{cash(data.kpis.outstanding_amount,data.currency)}</strong><small>Open invoice balances</small></Link><Link href="/invoices"><span>Overdue</span><strong>{cash(data.kpis.overdue_amount,data.currency)}</strong><small>Past their due date</small></Link><Link href="/invoices"><span>Paid invoices</span><strong>{data.kpis.paid_invoice_count}</strong><small>Completed invoices</small></Link></section><section className="dashboard-panels"><article className="panel"><div className="panel-heading"><div><span className="kicker">Cash flow</span><h2>Monthly receipts</h2></div></div><div className="bar-chart">{data.monthly_cash_flow.map(p=><div key={p.month} title={`${p.month}: ${cash(p.amount,data.currency)}`}><span style={{height:`${Math.max(3,Number(p.amount)/maxCash*100)}%`}}/><small>{new Date(p.month).toLocaleDateString("en-GB",{month:"short"})}</small></div>)}</div></article><article className="panel"><div className="panel-heading"><div><span className="kicker">Invoices</span><h2>Status breakdown</h2></div></div><div className="status-chart">{data.invoice_statuses.map(p=><button key={p.status} onClick={()=>setStatus(p.status)}><span>{p.status}<strong>{p.count}</strong></span><i><b style={{width:`${p.count/maxStatus*100}%`}}/></i><small>{cash(p.total_amount,data.currency)}</small></button>)}</div></article></section><section className="panel recent-panel"><div className="panel-heading"><div><span className="kicker">Latest</span><h2>Recent activity</h2></div></div>{data.recent_activity.length?<div className="activity-list">{data.recent_activity.map(a=><Link href={a.activity_type==="payment_received"?"/payments":"/invoices"} key={`${a.activity_type}-${a.entity_id}`}><span className="activity-dot">{a.activity_type==="payment_received"?"↓":"↑"}</span><span><strong>{a.description}</strong><small>{new Date(a.occurred_at).toLocaleString("en-GB")}</small></span><strong>{a.amount?cash(a.amount,data.currency):""}</strong></Link>)}</div>:<div className="compact-empty"><h3>No recent activity</h3><p>Invoices and payments will appear here.</p></div>}</section></>:null}</>}
