"""add created invoice to document processing

Revision ID: 1cc374a70b11
Revises: dfcae10d7d97
Create Date: 2026-08-11 11:11:51.788665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cc374a70b11'
down_revision: Union[str, Sequence[str], None] = 'dfcae10d7d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_processing', sa.Column('created_invoice_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_document_processing_created_invoice_id'), 'document_processing', ['created_invoice_id'], unique=True)
    op.create_foreign_key(
        'fk_document_processing_created_invoice_id_invoices',
        'document_processing',
        'invoices',
        ['created_invoice_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_document_processing_created_invoice_id_invoices',
        'document_processing',
        type_='foreignkey',
    )
    op.drop_index(op.f('ix_document_processing_created_invoice_id'), table_name='document_processing')
    op.drop_column('document_processing', 'created_invoice_id')
    # ### end Alembic commands ###
