"""create document processing table

Revision ID: dfcae10d7d97
Revises: fd0d53094845
Create Date: 2026-08-11 10:49:53.040816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfcae10d7d97'
down_revision: Union[str, Sequence[str], None] = 'fd0d53094845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_processing',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'review_required', 'completed', 'failed', name='document_processing_status'), server_default='pending', nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt_count >= 0', name='ck_document_processing_attempt_count_nonnegative'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', name='uq_document_processing_document_id')
    )
    op.create_index(op.f('ix_document_processing_document_id'), 'document_processing', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_processing_owner_id'), 'document_processing', ['owner_id'], unique=False)
    op.create_index(op.f('ix_document_processing_status'), 'document_processing', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_processing_status'), table_name='document_processing')
    op.drop_index(op.f('ix_document_processing_owner_id'), table_name='document_processing')
    op.drop_index(op.f('ix_document_processing_document_id'), table_name='document_processing')
    op.drop_table('document_processing')
    # ### end Alembic commands ###
